apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cxat1wolg-go-gitops
  description: This is GitOps manifest for cxat1wolg-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=cxat1wolg-go
    backstage.io/kubernetes-id: cxat1wolg-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: cxat1wolg-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cxat1wolg-go
